apiVersion: v1
kind: Service
metadata:
  name: temporal-app-directory-server-service
  labels:
    app: temporal-app-directory-server
spec:
  ports:
  - port: 3000
    name: server
  type: ClusterIP
  selector:
    app: temporal-app-directory-server