apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmprl-sa-cloud-server-staging
spec:
  secretName: tls-cert-tmprl-sa-cloud-server-staging
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - apps.tmprl-sa.cloud
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io