---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingressroute-reader
rules:
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-ingressroutes
subjects:
- kind: ServiceAccount
  name: default
  namespace: temporal-app-directory-server
roleRef:
  kind: ClusterRole
  name: ingressroute-reader
  apiGroup: rbac.authorization.k8s.io
